export const flagCodeByTeamCode: Record<string, string> = {
  ALG: 'dz',
  ARG: 'ar',
  AUS: 'au',
  AUT: 'at',
  BEL: 'be',
  BIH: 'ba',
  BOL: 'bo',
  BRA: 'br',
  CAN: 'ca',
  CHI: 'cl',
  CIV: 'ci',
  COD: 'cd',
  COL: 'co',
  CMR: 'cm',
  CPV: 'cv',
  CRC: 'cr',
  CRO: 'hr',
  CUW: 'cw',
  CZE: 'cz',
  DEN: 'dk',
  ECU: 'ec',
  EGY: 'eg',
  ENG: 'gb-eng',
  ESP: 'es',
  FRA: 'fr',
  GER: 'de',
  GHA: 'gh',
  HAI: 'ht',
  HON: 'hn',
  IRN: 'ir',
  IRQ: 'iq',
  JOR: 'jo',
  JPN: 'jp',
  KOR: 'kr',
  KSA: 'sa',
  JAM: 'jm',
  MAR: 'ma',
  MLI: 'ml',
  MEX: 'mx',
  NED: 'nl',
  NOR: 'no',
  NZL: 'nz',
  PAN: 'pa',
  PAR: 'py',
  POL: 'pl',
  POR: 'pt',
  QAT: 'qa',
  RSA: 'za',
  SCO: 'gb-sct',
  SEN: 'sn',
  SRB: 'rs',
  SUI: 'ch',
  SWE: 'se',
  TUN: 'tn',
  TUR: 'tr',
  URU: 'uy',
  USA: 'us',
  UAE: 'ae',
  UZB: 'uz'
};

export function flagIconCode(teamCode: unknown): string | null {
  if (typeof teamCode !== 'string') return null;
  return flagCodeByTeamCode[teamCode.toUpperCase()] ?? null;
}
