const teamCodeByName: Record<string, string> = {
  Algeria: 'ALG',
  Argentina: 'ARG',
  Australia: 'AUS',
  Austria: 'AUT',
  Belgium: 'BEL',
  Bolivia: 'BOL',
  Brazil: 'BRA',
  Cameroon: 'CMR',
  Canada: 'CAN',
  Chile: 'CHI',
  Colombia: 'COL',
  'Costa Rica': 'CRC',
  Croatia: 'CRO',
  Denmark: 'DEN',
  Ecuador: 'ECU',
  Egypt: 'EGY',
  England: 'ENG',
  France: 'FRA',
  Germany: 'GER',
  Ghana: 'GHA',
  Honduras: 'HON',
  Iran: 'IRN',
  Iraq: 'IRQ',
  Jamaica: 'JAM',
  Japan: 'JPN',
  Jordan: 'JOR',
  'Korea Republic': 'KOR',
  Mali: 'MLI',
  Mexico: 'MEX',
  Morocco: 'MAR',
  Netherlands: 'NED',
  'New Zealand': 'NZL',
  Norway: 'NOR',
  Panama: 'PAN',
  Paraguay: 'PAR',
  Poland: 'POL',
  Portugal: 'POR',
  Qatar: 'QAT',
  'Saudi Arabia': 'KSA',
  Scotland: 'SCO',
  Senegal: 'SEN',
  Serbia: 'SRB',
  'South Africa': 'RSA',
  Spain: 'ESP',
  Switzerland: 'SUI',
  Tunisia: 'TUN',
  UAE: 'UAE',
  'United States': 'USA',
  Uruguay: 'URU'
};

const teamNameEtByName: Record<string, string> = {
  Algeria: 'Alžeeria',
  Argentina: 'Argentina',
  Australia: 'Austraalia',
  Austria: 'Austria',
  Belgium: 'Belgia',
  Bolivia: 'Boliivia',
  Brazil: 'Brasiilia',
  Cameroon: 'Kamerun',
  Canada: 'Kanada',
  Chile: 'Tšiili',
  Colombia: 'Kolumbia',
  'Costa Rica': 'Costa Rica',
  Croatia: 'Horvaatia',
  Denmark: 'Taani',
  Ecuador: 'Ecuador',
  Egypt: 'Egiptus',
  England: 'Inglismaa',
  France: 'Prantsusmaa',
  Germany: 'Saksamaa',
  Ghana: 'Ghana',
  Honduras: 'Honduras',
  Iran: 'Iraan',
  Iraq: 'Iraak',
  Jamaica: 'Jamaica',
  Japan: 'Jaapan',
  Jordan: 'Jordaania',
  'Korea Republic': 'Lõuna-Korea',
  Mali: 'Mali',
  Mexico: 'Mehhiko',
  Morocco: 'Maroko',
  Netherlands: 'Holland',
  'New Zealand': 'Uus-Meremaa',
  Norway: 'Norra',
  Panama: 'Panama',
  Paraguay: 'Paraguay',
  Poland: 'Poola',
  Portugal: 'Portugal',
  Qatar: 'Katar',
  'Saudi Arabia': 'Saudi Araabia',
  Scotland: 'Šotimaa',
  Senegal: 'Senegal',
  Serbia: 'Serbia',
  Spain: 'Hispaania',
  Switzerland: 'Šveits',
  Tunisia: 'Tuneesia',
  UAE: 'AÜE',
  'United States': 'USA',
  Uruguay: 'Uruguay'
};

export function teamFromName(name: string) {
  const code = teamCodeByName[name];
  const displayName = teamNameEtByName[name] ?? name;
  return code ? { name: displayName, code } : { name: displayName };
}

export function displayTeamName(name: string) {
  return teamNameEtByName[name] ?? name;
}
